version: "3" 
services:
  view:
    container_name: "view" 
    build:
      context: ./view
      dockerfile: view.Dockerfile 
    volumes:
    - ./view:/view
    - ./view/node_modules:/view/node_modules
    command: sh -c "yarn && yarn start"
    ports:    
    - "3000:3000"
    stdin_open: true 
    tty: true 
    env_file:
      - ./view.env