blank_issues_enabled: false
contact_links:
  - name: Feature
    url: https://github.com/oyodai-games/ENEGIN/issues/new?template=issue_template.md
    about: Please create an issue using the default template.
